
api.auth.base=/auth
api.employees.base=/employees
api.departments.base=/departments
api.users.base=/users
api.dev.base=/dev

api.auth.login=/login
api.auth.logout=/logout

api.employees.get.by.id=/{id}
api.employees.get.by.employee.id=/employee-id/{employeeId}
api.employees.search=/search
api.employees.search.filter=/search-filter
api.employees.update=/{id}
api.employees.delete=/{id}
api.employees.activate=/{id}/activate
api.employees.report.department=/report/department/{departmentId}/paged
api.employees.report.age=/report/age/paged
api.employees.stats.salary=/stats/average-salary
api.employees.stats.age=/stats/average-age

api.departments.get.by.id=/{id}
api.departments.update=/{id}
api.departments.activate=/{id}/activate
api.departments.delete=/{id}

api.users.get.by.id=/{id}
api.users.search=/search
api.users.filter=/filter
api.users.search.filter=/search-filter
api.users.update=/{id}
api.users.delete=/{id}
api.users.activate=/{id}/activate

api.dev.seed=/seed